kind: pipline
name: Winsper-HeanService

steps:
- name: test
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
# - name: configuration
#   path: /drone/src/back-end/src/main/resources/application.yml
  commands:
  - mvn clean
  - mvn package -Dmaven.test.skip=true
  - echo "test and package hean-service completed 🙂🙂🙂"

- name: upload_master
  image: appleboy/drone-scp
  settings:
    host: 10.0.0.98
    username: root
    rm: true
    target: /Winsper/hean-service
    source:
      - target/hean-service-0.0.1-SNAPSHOT.jar
      - Dockerfile

- name: deploy_master
  image: appleboy/drone-ssh
  settings:
    host: 10.0.0.98
    username: root
    script:
      - cd /Winsper/hean-service/target
      - cp ../Dockerfile .
      - docker build -t winsper-hean-service .
      - docker rm -f winsper-hean-service-c

volumes:
- name: dependency
  host:
    path: /root/.m2
