kind: pipline
name: Winsper-HeanService

steps:
- name: test
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
# - name: configuration
#   path: /drone/src/back-end/src/main/resources/application.yml
  commands:
  - mvn clean
  - mvn package -Dmaven.test.skip=true
  - echo "test and package hean-service completed 🙂🙂🙂"

- name: upload_czn
  image: appleboy/drone-scp
  settings:
    host: 47.102.205.224
    username: root
    password:
      from_secret: czn_password
    rm: true
    target: /Winsper/hean-service
    source:
      - target/hean-service-0.0.1-SNAPSHOT.jar
      - Dockerfile

- name: deploy_czn
  image: appleboy/drone-ssh
  settings:
    host: 47.102.205.224
    username: root
    password:
      from_secret: czn_password
    script:
      - cd /Winsper/hean-service/target
      - cp ../Dockerfile .
      - docker build -t winsper-hean-service .
      - docker rm -f winsper-hean-service-c
      - docker run -d --name winsper-hean-service-c --expose=7190 -p 7190:7190 -e "EUREKA_INSTANCE_IP-ADDRESS=47.102.205.224" -e "SERVER_PORT=7190" winsper-hean-service

- name: upload_yjy
  image: appleboy/drone-scp
  settings:
    host: 47.103.0.246
    username: root
    password:
      from_secret: yjy_password
    rm: true
    target: /Winsper/hean-service
    source:
    - target/hean-service-0.0.1-SNAPSHOT.jar
    - Dockerfile

- name: deploy_yjy
  image: appleboy/drone-ssh
  settings:
    host: 47.103.0.246
    username: root
    password:
      from_secret: yjy_password
    script:
    - cd /Winsper/hean-service/target
    - cp ../Dockerfile .
    - docker build -t winsper-hean-service .
    - docker rm -f winsper-hean-service-c
    - docker run -d --name winsper-hean-service-c --expose=7190 -p 7190:7190 -e "EUREKA_INSTANCE_IP-ADDRESS=47.103.0.246" -e "SERVER_PORT=7190" winsper-hean-service

- name: upload_xyx
  image: appleboy/drone-scp
  settings:
    host: 101.132.176.33
    username: root
    password:
      from_secret: xyx_password
    rm: true
    target: /Winsper/hean-service
    source:
      - target/hean-service-0.0.1-SNAPSHOT.jar
      - Dockerfile

- name: deploy_xyx
  image: appleboy/drone-ssh
  settings:
    host: 101.132.176.33
    username: root
    password:
      from_secret: xyx_password
    script:
      - cd /Winsper/hean-service/target
      - cp ../Dockerfile .
      - docker build -t winsper-hean-service .
      - docker rm -f winsper-hean-service-c
      - docker run -d --name winsper-hean-service-c --expose=7190 -p 7190:7190 -e "EUREKA_INSTANCE_IP-ADDRESS=101.132.176.33" -e "SERVER_PORT=7190" winsper-hean-service

- name: upload_tbc
  image: appleboy/drone-scp
  settings:
    host: 47.100.126.180
    username: root
    password:
      from_secret: tbc_password
    rm: true
    target: /Winsper/hean-service
    source:
      - target/hean-service-0.0.1-SNAPSHOT.jar
      - Dockerfile

- name: deploy_tbc
  image: appleboy/drone-ssh
  settings:
    host: 47.100.126.180
    username: root
    password:
      from_secret: tbc_password
    script:
      - cd /Winsper/hean-service/target
      - cp ../Dockerfile .
      - docker build -t winsper-hean-service .
      - docker rm -f winsper-hean-service-c
      - docker run -d --name winsper-hean-service-c --expose=7190 -p 7190:7190 -e "EUREKA_INSTANCE_IP-ADDRESS=47.100.126.180" -e "SERVER_PORT=7190" winsper-hean-service

volumes:
- name: dependency
  host:
    path: /root/.m2