kind: pipline
name: Winsper-HeanService

steps:
- name: test
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
# - name: configuration
#   path: /drone/src/back-end/src/main/resources/application.yml
  commands:
  - cd /usr/share/maven/ref
  - ls
  - cat settings-docker.xml
  - mvn clean
  - mvn package -Dmaven.test.skip=true
  - echo "test and package hean-service completed 🙂🙂🙂"

- name: upload
  image: appleboy/drone-scp
  settings:
    host: 10.0.0.98
    username: root
    key: 
      from_secret: private_key
    rm: true
    target: /root/Winsper/drone-tmp
    source:
    - target/hean-service-0.0.1-SNAPSHOT.jar
    - Dockerfile

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 10.0.0.98
    username: root
    key: 
      from_secret: private_key
    script:
    - cd /root/Winsper/drone-tmp/target
    - cp ../Dockerfile .
    - docker build -t gusabary/winsper-hean .
    - docker login
    - docker push gusabary/winsper-hean
    - cd /root/Winsper/Winsper
    - kubectl delete deploy/winsper-hean
    - kubectl apply -f hean-deployment.yml

volumes:
- name: dependency
  host:
    path: /root/.m2